In [1]:
import numpy as np 
import pandas as pd

In [2]:
dataset = pd.read_csv('./Dataset/fraud test.csv')
dataset.head(5)

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,21/06/2020 12:14,2.291160e+15,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,...,33.9659,-80.9355,333497,Mechanical engineer,19/03/1968,2da90c7d74bd46a0caf3777415b3ebd3,1371816865,33.986391,-81.200714,0
1,1,21/06/2020 12:14,3.573030e+15,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,...,40.3207,-110.4360,302,"Sales professional, IT",17/01/1990,324cc204407e99f51b0d6ca0055005e7,1371816873,39.450498,-109.960431,0
2,2,21/06/2020 12:14,3.598220e+15,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,9333 Valentine Point,...,40.6729,-73.5365,34496,"Librarian, public",21/10/1970,c81755dbbbea9d5c77f094348a7579be,1371816893,40.495810,-74.196111,0
3,3,21/06/2020 12:15,3.591920e+15,fraud_Haley Group,misc_pos,60.05,Brian,Williams,M,32941 Krystal Mill Apt. 552,...,28.5697,-80.8191,54767,Set designer,25/07/1987,2159175b9efe66dc301f149d3d5abf8c,1371816915,28.812398,-80.883061,0
4,4,21/06/2020 12:15,3.526830e+15,fraud_Johnston-Casper,travel,3.19,Nathan,Massey,M,5783 Evan Roads Apt. 465,...,44.2529,-85.0170,1126,Furniture designer,06/07/1955,57ff021bd3f328f8738bb535c302a31b,1371816917,44.959148,-85.884734,0

In [3]:
dataset = dataset.drop(['trans_date_trans_time', 'cc_num', 'trans_num'], axis=1)
dataset.head(5)

,Unnamed: 0,merchant,category,amt,first,last,gender,street,city,state,zip,lat,long,city_pop,job,dob,unix_time,merch_lat,merch_long,is_fraud
0,0,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,Columbia,SC,29209,33.9659,-80.9355,333497,Mechanical engineer,19/03/1968,1371816865,33.986391,-81.200714,0
1,1,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,Altonah,UT,84002,40.3207,-110.4360,302,"Sales professional, IT",17/01/1990,1371816873,39.450498,-109.960431,0
2,2,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,9333 Valentine Point,Bellmore,NY,11710,40.6729,-73.5365,34496,"Librarian, public",21/10/1970,1371816893,40.495810,-74.196111,0
3,3,fraud_Haley Group,misc_pos,60.05,Brian,Williams,M,32941 Krystal Mill Apt. 552,Titusville,FL,32780,28.5697,-80.8191,54767,Set designer,25/07/1987,1371816915,28.812398,-80.883061,0
4,4,fraud_Johnston-Casper,travel,3.19,Nathan,Massey,M,5783 Evan Roads Apt. 465,Falmouth,MI,49632,44.2529,-85.0170,1126,Furniture designer,06/07/1955,1371816917,44.959148,-85.884734,0

In [4]:
from datetime import datetime
def calculate_age(dob):
    today = datetime.today()
    dob = datetime.strptime(dob, '%d/%m/%Y')  
    age = today.year - dob.year - ((today.month, today.day) < (dob.month, dob.day))
    return age

dataset['Age'] = dataset['dob'].apply(calculate_age)

dataset= dataset.drop('dob', axis=1)
dataset.head(5)

,Unnamed: 0,merchant,category,amt,first,last,gender,street,city,state,zip,lat,long,city_pop,job,unix_time,merch_lat,merch_long,is_fraud,Age
0,0,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,Columbia,SC,29209,33.9659,-80.9355,333497,Mechanical engineer,1371816865,33.986391,-81.200714,0,56
1,1,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,Altonah,UT,84002,40.3207,-110.4360,302,"Sales professional, IT",1371816873,39.450498,-109.960431,0,34
2,2,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,9333 Valentine Point,Bellmore,NY,11710,40.6729,-73.5365,34496,"Librarian, public",1371816893,40.495810,-74.196111,0,53
3,3,fraud_Haley Group,misc_pos,60.05,Brian,Williams,M,32941 Krystal Mill Apt. 552,Titusville,FL,32780,28.5697,-80.8191,54767,Set designer,1371816915,28.812398,-80.883061,0,36
4,4,fraud_Johnston-Casper,travel,3.19,Nathan,Massey,M,5783 Evan Roads Apt. 465,Falmouth,MI,49632,44.2529,-85.0170,1126,Furniture designer,1371816917,44.959148,-85.884734,0,68

In [5]:
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer

columns_to_encode = ['merchant', 'category', 'first', 'last', 'gender', 'street', 'city', 'state', 'job']

label_encoders = {col: LabelEncoder() for col in columns_to_encode}

for col in columns_to_encode:
    dataset[col] = label_encoders[col].fit_transform(dataset[col])
    
dataset.head(5)

,Unnamed: 0,merchant,category,amt,first,last,gender,street,city,state,zip,lat,long,city_pop,job,unix_time,merch_lat,merch_long,is_fraud,Age
0,0,319,10,2.86,151,115,1,341,157,39,29209,33.9659,-80.9355,333497,275,1371816865,33.986391,-81.200714,0,56
1,1,591,10,29.84,163,457,0,354,16,43,84002,40.3207,-110.4360,302,392,1371816873,39.450498,-109.960431,0,34
2,2,611,5,41.28,24,249,0,865,61,33,11710,40.6729,-73.5365,34496,259,1371816893,40.495810,-74.196111,0,53
3,3,222,9,60.05,42,457,1,320,764,8,32780,28.5697,-80.8191,54767,407,1371816915,28.812398,-80.883061,0,36
4,4,292,13,3.19,247,261,1,548,247,21,49632,44.2529,-85.0170,1126,196,1371816917,44.959148,-85.884734,0,68

In [6]:
Y = dataset['is_fraud']
dataset = dataset.drop(['is_fraud'], axis=1)
X = dataset.iloc[:, 1:18 ].values

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state=0)

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [9]:
from sklearn.ensemble import RandomForestClassifier

rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)
rf_classifier.fit(X_train, Y_train)

RandomForestClassifier(random_state=42)

In [10]:
y_pred = rf_classifier.predict(X_test)

In [11]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(Y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.9981825379687612

In [12]:
# import pickle

# with open('rf_classifier.pkl', 'wb') as f:
#     pickle.dump(rf_classifier, f)
import joblib

joblib.dump(rf_classifier, 'model.pkl')

['model.pkl']

In [14]:
# with open('label_encoders.pkl', 'wb') as f:
#     pickle.dump(label_encoders, f)